// Single import point for the engine artifact. The JSON is generated by the
// prebuild step (engine/run.ts); the UI never recomputes or reads the CSVs.
import data from "@/app/_generated/accrualRun.json";
import type { AccrualRun } from "@/engine/types";

export const accrualRun = data as unknown as AccrualRun;
